language: ruby
cache: bundler
dist: trusty
sudo: required
services:
  - docker
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable
rvm:
- 2.5.1
script:
- bundle exec jekyll build
notifications:
  email: false
  
